name: Build and Test Backend

on:
   push:
      branches: [main, develop]
      paths:
         - "Backend/**"
         - "Backend.Tests/**"
   pull_request:
      branches: [main]
      paths:
         - "Backend/**"
         - "Backend.Tests/**"

jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v4

         - name: Setup .NET
           uses: actions/setup-dotnet@v4
           with:
              dotnet-version: "8.0.x"

         - name: Restore dependencies
           run: dotnet restore Backend/backend.csproj

         - name: Build
           run:
              dotnet build Backend/backend.csproj --no-restore --configuration
              Release

         - name: Test
           run:
              dotnet test Backend.Tests/Backend.Tests.csproj --no-build
              --configuration Release --verbosity normal

   build-docker:
      runs-on: ubuntu-latest
      needs: test

      steps:
         - uses: actions/checkout@v4

         - name: Build Docker image
           run: |
              cd Backend
              docker build -t bookstore-api:${{ github.sha }} .

         - name: Test Docker image
           run: |
              docker run -d -p 8080:8080 --name test-container bookstore-api:${{ github.sha }}
              sleep 10
              curl -f http://localhost:8080/health || exit 1
              docker stop test-container
